filter:
    excluded_paths:
        - 'tests/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                concatenation: true

build:
    environment:
        php: '5.6.16'

tools:
    external_code_coverage: true